### ISSUE TITLE
The custom device name control appears editable, but it is not

### ISSUE THREAD

**Issue by rtzoeller** [ni/niveristand-slsc-12201-custom-device#13]
The custom device name appears editable, but it is not. 
![image](https://user-images.githubusercontent.com/573497/55656770-c9f19900-57bd-11e9-81aa-76be68b50d3e.png)

**Comment by Alexbarp** [comment]
I propose that the fix should be to allow editing the name for versions above VS 2017. The EDS Custom Device does that and it should allowed here too. For previous versions (VS 2015 and VS 2016), if you change the name, the SLSC Chassis Custom Device will "hang" the system. So, that is the reason this was not allowed then.

**Comment by Karl-G1** [comment]
For now, let's change the Name control to an indicator on the main page. When we drop 2016 build support (presumably for the next major year release), we will change it back to a control and enable the name change behavior.

**Comment by Alexbarp** [comment]
Hey @Karl-G1 , I would think that we can do a very simple 'trick'. We can check for 2016 and previous and, then use the "disable and grey out". This will give the impression that is not editable. And for 2017 and after, then allow editing properly. The reason I say that is because I think we should penalize the users of the latest version of an important feature to have in VeriStand that was supposed to be worked in previous versions. If you have question to implement, let me know... I would be happy to do it.
